-- the first script for migration
-- For h2 db use, move to replace file in migration
create table Quip (
    id bigint generated by default as identity,
    content varchar(10000),
    score bigint,
    source varchar(255),
    postedAt timestamp,
    sourceDate timestamp,
    primary key (id)
);

create table Quip_authorIds (
    Quip_id bigint not null,
    authorIds bigint
);
   
create table User (
    id bigint generated by default as identity,
    fullname varchar(255),
    isAdmin boolean not null,
    password varchar(255),
    username varchar(255),
    primary key (id)
);
    
alter table Quip_authorIds
add constraint FK_f9ivk719aqb0rqd8my08loev7 
foreign key (Quip_id)
references Quip;
